ARG project_id
ARG android_version
FROM gcr.io/${project_id}/android:${android_version}-ndk-r17b

# Install JRE 11 at /usr/lib/jvm/jdk-11
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/openjdk-11_bin.tar.gz https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz
RUN tar xvf /tmp/openjdk-11_bin.tar.gz
RUN sudo mv jdk-11 /usr/lib/jvm
RUN rm /tmp/openjdk-11_bin.tar.gz

RUN apt-get update && \
    apt-get install -y tar bzip2 gzip

ENV JAVA_HOME /usr/lib/jvm/jdk-11

# Set environment variables
ENV PATH=${ANDROID_HOME}/build-tools/28.0.3:${PATH}