ARG project_id
ARG android_version
FROM gcr.io/${project_id}/android:${android_version}-ndk-r17b

# Install JRE 11 at /usr/lib/jvm/jdk-11
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/openjdk-11_bin.tar.gz 
RUN tar xvf /tmp/openjdk-11_bin.tar.gz
RUN sudo mv jdk-11 /usr/lib/jvm
RUN rm /tmp/openjdk-11_bin.tar.gz

RUN apt-get update && \
    apt-get install -y tar bzip2 gzip

ENV JAVA_HOME /usr/lib/jvm/jdk-11